### ISSUE TITLE
OpenRA crashes after clicking RA2

### ISSUE THREAD

**Issue by Zjebski** [OpenRA/ra2#140]
Every time I click on RA2 I get the same error: System.IO.InvalidDataException: Duplicate key 'ra2'
It happens when I use both the latest release and the latest playtest of RA2

Here is the full log:

`Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.IO.InvalidDataException`: Duplicate key 'ra2' in C:\Program Files (x86)\OpenRA\mods\ra2\mod.yaml:39
Inner Exception of type `System.ArgumentException`: An item with the same key has already been added.
     at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OpenRA.MiniYaml.ToDictionary[TKey,TElement](Func`2 keySelector, Func`2 elementSelector)
   at OpenRA.MiniYaml.ToDictionary[TKey,TElement](Func`2 keySelector, Func`2 elementSelector)
   at OpenRA.Manifest.YamlDictionary(Dictionary`2 yaml, String key, Boolean parsePaths)
   at OpenRA.Manifest..ctor(String mod)
   at OpenRA.ModData..ctor(String mod, Boolean useLoadScreen)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Mods.Common.Widgets.Logic.ModBrowserLogic.<LoadMod>c__AnonStorey1.<>m__0()
   at OpenRA.Primitives.ActionQueue.PerformActions(Int32 currentTime)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
`

Any way of fixing this? I really wanna add RA2 to OpenRA...

**Comment by abcdefg30** [comment]
This mod does not work with the latest release/playtest (unfortunately).
You need the (latest) development version of OpenRA, see https://github.com/OpenRA/OpenRA/wiki/Compiling and https://github.com/OpenRA/ra2/wiki.
