### ISSUE TITLE
Nuke Crash

### ISSUE THREAD

**Issue by steadyfield** [OpenRA/ra2#197]
Red Alert 2 Mod at Version {DEV_VERSION}
on map bddba977616ef17d88e69249020b3e0bb9252a8b (Valley by Westwood Studios).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.InvalidOperationException`: Unit `beacon` does not have a sequence named `arrow`
   at OpenRA.Graphics.SequenceProvider.GetSequence(String unitName, String sequenceName) in d:\git\OpenRA-bleed-5-1\OpenRA.Game\Graphics\SequenceProvider.cs:Line 77
   at OpenRA.Graphics.Animation.GetSequence(String sequenceName) in d:\git\OpenRA-bleed-5-1\OpenRA.Game\Graphics\Animation.cs:Line 206
   at OpenRA.Graphics.Animation.PlaySequence(String sequenceName) in d:\git\OpenRA-bleed-5-1\OpenRA.Game\Graphics\Animation.cs:Line 87
   at OpenRA.Graphics.Animation.PlayThen(String sequenceName, Action after) in d:\git\OpenRA-bleed-5-1\OpenRA.Game\Graphics\Animation.cs:Line 121
   at OpenRA.Graphics.Animation.Play(String sequenceName) in d:\git\OpenRA-bleed-5-1\OpenRA.Game\Graphics\Animation.cs:Line 76
   at OpenRA.Mods.Common.Effects.Beacon..ctor(Player owner, WPos position, Int32 duration, String beaconPalette, Boolean isPlayerPalette, String beaconCollection, String arrowSprite, String circleSprite)
   at OpenRA.Mods.Common.Effects.Beacon..ctor(Player owner, WPos position, Boolean isPlayerPalette, String palette, String posterCollection, String posterType, String posterPalette, String arrowSequence, String circleSequence, String clockSequence, Func`1 clockFraction)
   at OpenRA.Mods.Common.Traits.NukePower.Activate(Actor self, Order order, SupportPowerManager manager)
   at OpenRA.Mods.Common.Traits.SupportPowerInstance.Activate(Order order)
   at OpenRA.Mods.Common.Traits.SupportPowerManager.ResolveOrder(Actor self, Order order)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) in d:\git\OpenRA-bleed-5-1\OpenRA.Game\Network\UnitOrders.cs:Line 281
   at OpenRA.Network.OrderManager.Tick() in d:\git\OpenRA-bleed-5-1\OpenRA.Game\Network\OrderManager.cs:Line 178
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in d:\git\OpenRA-bleed-5-1\OpenRA.Game\Game.cs:Line 514
   at OpenRA.Game.LogicTick() in d:\git\OpenRA-bleed-5-1\OpenRA.Game\Game.cs:Line 547
   at OpenRA.Game.Loop() in d:\git\OpenRA-bleed-5-1\OpenRA.Game\Game.cs:Line 674
   at OpenRA.Game.Run() in d:\git\OpenRA-bleed-5-1\OpenRA.Game\Game.cs:Line 714
   at OpenRA.Program.Run(String[] args) in d:\git\OpenRA-bleed-5-1\OpenRA.Game\Support\Program.cs:Line 118
   at OpenRA.Program.Main(String[] args) in d:\git\OpenRA-bleed-5-1\OpenRA.Game\Support\Program.cs:Line 40

**Comment by jtyle6** [comment]
```
Red Alert 2 Mod at Version {DEV_VERSION}
on map 2e19dd9bcba0c57d5cfc7d1f03c0ce06837685b7 (Powder Keg by Westwood Studios).
Operating System: OSX (Unix 14.5.0.0)
Runtime Version: Mono 4.4.0 (mono-4.4.0-branch/a3fabf1 Fri Apr  8 13:48:29 EDT 2016) CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Unit `beacon` does not have a sequence named `arrow`
  at OpenRA.Graphics.SequenceProvider.GetSequence (System.String unitName, System.String sequenceName) [0x0006b] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Graphics/SequenceProvider.cs:80 
  at OpenRA.Graphics.Animation.GetSequence (System.String sequenceName) [0x0000e] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Graphics/Animation.cs:206 
  at OpenRA.Graphics.Animation.PlaySequence (System.String sequenceName) [0x00004] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Graphics/Animation.cs:87 
  at OpenRA.Graphics.Animation.PlayThen (System.String sequenceName, System.Action after) [0x00025] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Graphics/Animation.cs:121 
  at OpenRA.Graphics.Animation.Play (System.String sequenceName) [0x00004] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Graphics/Animation.cs:76 
  at OpenRA.Mods.Common.Effects.Beacon..ctor (OpenRA.Player owner, WPos position, Int32 duration, System.String beaconPalette, Boolean isPlayerPalette, System.String beaconCollection, System.String arrowSprite, System.String circleSprite) <0x13b94828 + 0x001bf> in <filename unknown>:0 
  at OpenRA.Mods.Common.Effects.Beacon..ctor (OpenRA.Player owner, WPos position, Boolean isPlayerPalette, System.String palette, System.String posterCollection, System.String posterType, System.String posterPalette, System.String arrowSequence, System.String circleSequence, System.String clockSequence, System.Func`1 clockFraction) <0x13b94590 + 0x0009f> in <filename unknown>:0 
  at OpenRA.Mods.Common.Traits.NukePower.Activate (OpenRA.Actor self, OpenRA.Order order, OpenRA.Mods.Common.Traits.SupportPowerManager manager) <0x13b92fb0 + 0x00b2f> in <filename unknown>:0 
  at OpenRA.Mods.Common.Traits.SupportPowerInstance.Activate (OpenRA.Order order) <0x13b92e10 + 0x000b2> in <filename unknown>:0 
  at OpenRA.Mods.Common.Traits.SupportPowerManager.ResolveOrder (OpenRA.Actor self, OpenRA.Order order) <0x130d3960 + 0x00057> in <filename unknown>:0 
  at OpenRA.Network.UnitOrders.ProcessOrder (OpenRA.Network.OrderManager orderManager, OpenRA.World world, Int32 clientId, OpenRA.Order order) [0x00bf7] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Network/UnitOrders.cs:281 
  at OpenRA.Network.OrderManager.Tick () [0x000a1] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Network/OrderManager.cs:178 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00204] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Game.cs:514 
  at OpenRA.Game.LogicTick () [0x00055] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Game.cs:547 
  at OpenRA.Game.Loop () [0x000d4] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Game.cs:674 
  at OpenRA.Game.Run () [0x00042] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Game.cs:714 
  at OpenRA.Program.Run (System.String[] args) [0x00011] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Support/Program.cs:118 
  at OpenRA.Program.Main (System.String[] args) [0x00050] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Support/Program.cs:40 
```
