### ISSUE TITLE
ra2 mod crashes when configuring assets

### ISSUE THREAD

**Issue by JHouterman** [OpenRA/ra2#296]
Hi guys,

I'm trying to run the ra2 mod, i get to the main menu, which has the ra2 icon, but when i try to configure the content, the game crashes. Exception logs says:

Mod Chooser Mod at Version {DEV_VERSION}
Date: 2016-09-11 10:08:10Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34014
Exception of type `System.Reflection.TargetInvocationException`: Exception has been thrown by the target of an invocation.
Inner Exception of type `System.IO.FileNotFoundException`: File not found: ra2
     at OpenRA.FileSystem.FileSystem.Open(String filename) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\FileSystem\FileSystem.cs:line 228
   at OpenRA.MiniYaml.<>c__DisplayClass28.<Load>b__27(String s) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\MiniYaml.cs:line 390
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at OpenRA.MiniYaml.Merge(IEnumerable`1 sources) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\MiniYaml.cs:line 262
   at OpenRA.MiniYaml.Load(IReadOnlyFileSystem fileSystem, IEnumerable`1 files, MiniYaml mapRules) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\MiniYaml.cs:line 394
   at OpenRA.Mods.Common.Widgets.Logic.ModContentLogic..ctor(Widget widget, Manifest mod, ModContent content, Action onCancel)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at OpenRA.ObjectCreator.CreateUsingArgs(ConstructorInfo ctor, Dictionary`2 args) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\ObjectCreator.cs:line 140
   at OpenRA.ObjectCreator.CreateObject[T](String className, Dictionary`2 args) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\ObjectCreator.cs:line 105
   at OpenRA.Widgets.Widget.<>c__DisplayClass3.<PostInit>b__2(String l) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:line 274
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenRA.Widgets.Widget.PostInit(WidgetArgs args) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:line 274
   at OpenRA.WidgetLoader.LoadWidget(WidgetArgs args, Widget parent, MiniYamlNode node) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Widgets\WidgetLoader.cs:line 75
   at OpenRA.WidgetLoader.LoadWidget(WidgetArgs args, Widget parent, String w) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Widgets\WidgetLoader.cs:line 44
   at OpenRA.Widgets.Ui.OpenWindow(String id, WidgetArgs args) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:line 62
   at OpenRA.Mods.Common.Widgets.Logic.ModContentPromptLogic.<>c__DisplayClassa.<.ctor>b__3()
   at OpenRA.Mods.Common.Widgets.ButtonWidget.<.ctor>b__e(MouseInput _)
   at OpenRA.Mods.Common.Widgets.ButtonWidget.HandleMouseInput(MouseInput mi)
   at OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:line 393
   at OpenRA.Widgets.Ui.HandleInput(MouseInput mi) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:line 102
   at OpenRA.DefaultInputHandler.<>c__DisplayClass7.<OnMouseInput>b__6() in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Input\InputHandler.cs:line 50
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Sync.cs:line 174
   at OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Input\InputHandler.cs:line 50
   at OpenRA.Platforms.Default.Sdl2Input.PumpInput(IInputHandler inputHandler) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Platforms.Default\Sdl2Input.cs:line 107
   at OpenRA.Platforms.Default.Sdl2GraphicsDevice.PumpInput(IInputHandler inputHandler) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Platforms.Default\Sdl2GraphicsDevice.cs:line 365
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Renderer.cs:line 155
   at OpenRA.Game.RenderTick() in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Game.cs:line 624
   at OpenRA.Game.Loop() in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Game.cs:line 734
   at OpenRA.Game.Run() in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Game.cs:line 752
   at OpenRA.Program.Run(String[] args) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 119
   at OpenRA.Program.Main(String[] args) in c:\Users\JoepH\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 40

If this is a duplicate, please inform me, i found errors that are similar, but not exactly the same.

Thanks in advance

**Comment by Phrohdoh** [comment]
> but when i try to configure the content

What exactly do you mean by this?
Once you are in the game there is nothing to configure regarding the original assets.

**Comment by abcdefg30** [comment]
I assume he refers to the "Manage Content" button in the modchooser.

**Comment by JHouterman** [comment]
Correct!

**Comment by LipkeGu** [comment]
We could enable installations with TFD discs and:
https://github.com/OpenRA/OpenRA/pull/12099

**Comment by drifthat** [comment]
this issue should be fixed by https://github.com/OpenRA/ra2/pull/355
