### ISSUE TITLE
do not run

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/ra2#306]
in yesturday playtest and last dev:

Date: 2016-10-02 15:32:26Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.ArgumentException`: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at OpenRA.FileSystem.Folder.Contains(String filename) in d:\Games\OpenRA-bleed\OpenRA.Game\FileSystem\Folder.cs:line 49
   at OpenRA.FileSystem.FileSystem.<>c__DisplayClass13.<TryOpen>b__12(IReadOnlyPackage x) in d:\Games\OpenRA-bleed\OpenRA.Game\FileSystem\FileSystem.cs:line 268
   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenRA.FileSystem.FileSystem.TryOpen(String filename, Stream& s) in d:\Games\OpenRA-bleed\OpenRA.Game\FileSystem\FileSystem.cs:line 268
   at OpenRA.FileSystem.FileSystem.Open(String filename) in d:\Games\OpenRA-bleed\OpenRA.Game\FileSystem\FileSystem.cs:line 227
   at OpenRA.ObjectCreator..ctor(Manifest manifest, FileSystem modFiles) in d:\Games\OpenRA-bleed\OpenRA.Game\ObjectCreator.cs:line 49
   at OpenRA.ModData..ctor(Manifest mod, InstalledMods mods, Boolean useLoadScreen) in d:\Games\OpenRA-bleed\OpenRA.Game\ModData.cs:line 58
   at OpenRA.Game.InitializeMod(String mod, Arguments args) in d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:line 373
   at OpenRA.Mods.Common.Widgets.Logic.ModBrowserLogic.<>c__DisplayClass2f.<LoadMod>b__2d()
   at OpenRA.Primitives.ActionQueue.PerformActions(Int64 currentTime) in d:\Games\OpenRA-bleed\OpenRA.Game\Primitives\ActionQueue.cs:line 53
   at OpenRA.Game.LogicTick() in d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:line 577
   at OpenRA.Game.Loop() in d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:line 712
   at OpenRA.Game.Run() in d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:line 752
   at OpenRA.Program.Run(String[] args) in d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 134
   at OpenRA.Program.Main(String[] args) in d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 41

**Comment by abcdefg30** [comment]
> in yesturday playtest 

The mod won't run in the playtest anyway, as the `ts.dll` is missing.
It looks like the `ra2.dll` (or another dll) is missing here. Could you check if it (they) exist?

**Comment by yaaaaa** [comment]
I remove RA2 mod and reinstall d2 mod, and first time then it starts in playtest:
![image](https://cloud.githubusercontent.com/assets/11130958/19028422/97a34236-895d-11e6-8cac-068e904c1f45.png)

in another time then it starts in playtest or everytime in dev:
Date: 2016-10-03 05:47:56Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.Reflection.ReflectionTypeLoadException`: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at OpenRA.Exts.GetNamespaces(Assembly a) in d:\Games\OpenRA-bleed\OpenRA.Game\Exts.cs:line 52
   at OpenRA.ObjectCreator.<.ctor>b__6(Assembly asm) in d:\Games\OpenRA-bleed\OpenRA.Game\ObjectCreator.cs:line 71
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenRA.ObjectCreator..ctor(Manifest manifest, FileSystem modFiles) in d:\Games\OpenRA-bleed\OpenRA.Game\ObjectCreator.cs:line 71
   at OpenRA.ModData..ctor(Manifest mod, InstalledMods mods, Boolean useLoadScreen) in d:\Games\OpenRA-bleed\OpenRA.Game\ModData.cs:line 58
   at OpenRA.Game.InitializeMod(String mod, Arguments args) in d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:line 373
   at OpenRA.Mods.Common.Widgets.Logic.ModBrowserLogic.<>c__DisplayClass2f.<LoadMod>b__2d()
   at OpenRA.Primitives.ActionQueue.PerformActions(Int64 currentTime) in d:\Games\OpenRA-bleed\OpenRA.Game\Primitives\ActionQueue.cs:line 53
   at OpenRA.Game.LogicTick() in d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:line 577
   at OpenRA.Game.Loop() in d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:line 712
   at OpenRA.Game.Run() in d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:line 752
   at OpenRA.Program.Run(String[] args) in d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 134
   at OpenRA.Program.Main(String[] args) in d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 41

**Comment by abcdefg30** [comment]
> I remove RA2 mod and reinstall d2 mod

Why d2? And as already said, the ra2 mod won't run with the playtest.
Did you compile the ra2.dll/does it exist inside your mod directory?

**Comment by yaaaaa** [comment]
OMG, sorry, ra2 mod is work to me, mistake place for this issue.

**Comment by abcdefg30** [comment]
:smile: no problem.
