### ISSUE TITLE
RA2 Crash

### ISSUE THREAD

**Issue by AlexDenthanor** [OpenRA/ra2#307]
I've tried to compile it following the instructions on the github wiki, however after spending several hours, I could not get the ra2 to compile, when I would launch the cake, the cmd log would appear as a black screen for about 10 seconds, then simply close. I've found no way around this.
So, I then attempted to utilize the ra2-tibsunmaster folder. I compiled it, but every time I would get around 105 errors. Tiberian Sun would run perfectly fine (tested several multiplayer games with friends) but no matter what I did, Red Alert 2 would simply no longer launch.
So, now I have the bleeds version compiled. I have ra2 master (renamed to just ra2) in the openra/mods folder. I have the .mix files where they need to be, but the damnable thing still will not launch properly. For some reason I can't upload my .zip or the .log files, so here:

Date: 2016-10-15 04:29:16Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.ArgumentException`: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at OpenRA.FileSystem.Folder.Contains(String filename) in c:\Users\Alexhandr\Desktop\OpenRA-bleed\OpenRA.Game\FileSystem\Folder.cs:line 49
   at OpenRA.FileSystem.FileSystem.<>c__DisplayClass13.<TryOpen>b__12(IReadOnlyPackage x) in c:\Users\Alexhandr\Desktop\OpenRA-bleed\OpenRA.Game\FileSystem\FileSystem.cs:line 268
   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenRA.FileSystem.FileSystem.TryOpen(String filename, Stream& s) in c:\Users\Alexhandr\Desktop\OpenRA-bleed\OpenRA.Game\FileSystem\FileSystem.cs:line 268
   at OpenRA.FileSystem.FileSystem.Open(String filename) in c:\Users\Alexhandr\Desktop\OpenRA-bleed\OpenRA.Game\FileSystem\FileSystem.cs:line 227
   at OpenRA.ObjectCreator..ctor(Manifest manifest, FileSystem modFiles) in c:\Users\Alexhandr\Desktop\OpenRA-bleed\OpenRA.Game\ObjectCreator.cs:line 46
   at OpenRA.ModData..ctor(Manifest mod, InstalledMods mods, Boolean useLoadScreen) in c:\Users\Alexhandr\Desktop\OpenRA-bleed\OpenRA.Game\ModData.cs:line 58
   at OpenRA.Game.InitializeMod(String mod, Arguments args) in c:\Users\Alexhandr\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 372
   at OpenRA.Mods.Common.Widgets.Logic.ModBrowserLogic.<>c__DisplayClass2f.<LoadMod>b__2d()
   at OpenRA.Primitives.ActionQueue.PerformActions(Int64 currentTime) in c:\Users\Alexhandr\Desktop\OpenRA-bleed\OpenRA.Game\Primitives\ActionQueue.cs:line 53
   at OpenRA.Game.LogicTick() in c:\Users\Alexhandr\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 576
   at OpenRA.Game.Loop() in c:\Users\Alexhandr\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 711
   at OpenRA.Game.Run() in c:\Users\Alexhandr\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 751
   at OpenRA.Program.Run(String[] args) in c:\Users\Alexhandr\Desktop\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 134
   at OpenRA.Program.Main(String[] args) in c:\Users\Alexhandr\Desktop\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 41

**Comment by abcdefg30** [comment]
Yeah, this crash occures when the dll is not compiled.
Could you try running the make file from the console (so it doesn't close after failing)? We might get to see an error that way. (I also assume you installed cake already.)

**Comment by AlexDenthanor** [comment]
The error I received was "Error: The target '$command' was not found.

**Comment by abcdefg30** [comment]
Weird, I can't reproduce this on my end. So this happens when you just run `make.cmd`?

**Comment by AlexDenthanor** [comment]
Yes.
![makecmderror](https://cloud.githubusercontent.com/assets/19152758/19419179/0a3bd776-93a0-11e6-8409-bb391b497def.PNG)

**Comment by AlexDenthanor** [comment]
Issue has been resolved. Redownloaded both Bleed & ra2 master. A file was missing from my original install: build.cake. Got it in the new download. From mods/ra2 I right clicked build.cake, opened with Cake.exe, told it where my OpenRaBleed was, and it installed and everything works fine now.
