### ISSUE TITLE
System.MissingFieldException: Field not found: 'OpenRA.World.ActorMap'

### ISSUE THREAD

**Issue by thefloe1** [OpenRA/ra2#376]
Build latest Version of RA2 and OpenRA.  When building war factory the game crashes with following exception:

Red Alert 2 Mod at Version {DEV_VERSION}
on map 7c8e7a330adc911200225027aa2ce111971fe629 (Tsunami by Westwood Studios).
Date: 2017-03-27 13:06:56Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.MissingFieldException`: Field not found: 'OpenRA.World.ActorMap'.
   at OpenRA.Mods.RA2.Traits.WithExitOverlay.Tick(Actor self)
   at OpenRA.World.<Tick>b__a(TraitPair`1 x) in d:\Downloads\OpenRA2\OpenRA-bleed\OpenRA.Game\World.cs:line 344
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) in d:\Downloads\OpenRA2\OpenRA-bleed\OpenRA.Game\WorldUtils.cs:line 75
   at OpenRA.World.Tick() in d:\Downloads\OpenRA2\OpenRA-bleed\OpenRA.Game\World.cs:line 0
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in d:\Downloads\OpenRA2\OpenRA-bleed\OpenRA.Game\Game.cs:line 587
   at OpenRA.Game.LogicTick() in d:\Downloads\OpenRA2\OpenRA-bleed\OpenRA.Game\Game.cs:line 611
   at OpenRA.Game.Loop() in d:\Downloads\OpenRA2\OpenRA-bleed\OpenRA.Game\Game.cs:line 738
   at OpenRA.Game.Run() in d:\Downloads\OpenRA2\OpenRA-bleed\OpenRA.Game\Game.cs:line 778
   at OpenRA.Program.Run(String[] args) in d:\Downloads\OpenRA2\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 133
   at OpenRA.Program.Main(String[] args) in d:\Downloads\OpenRA2\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 40

Edit: also just happens after some time when not building warfactory. Happens on different maps and different fractions.

**Comment by abcdefg30** [comment]
I can't reproduce the crash on my end. Are you sure that you have all dependencies correctly installed?

**Comment by thefloe1** [comment]
I now deleted the ra2 folder from mods, unpacked the repo and built it again and now the error is gone. No idea what was wrong last time...

**Comment by abcdefg30** [comment]
Ok, at least it works now. ^^
