### ISSUE TITLE
RA2 Mod crashes on launch

### ISSUE THREAD

**Issue by alexholliz** [OpenRA/ra2#388]
Was able to build and start the RA2 mod on Windows 10; it successfully imported the appropriate .mix files.
However, after the content install, and restarting the mod, it crashes on startup every time. I have attached two log files from my last 2 launches.
[exception-2017-06-05T072137Z.txt](https://github.com/OpenRA/ra2/files/1051354/exception-2017-06-05T072137Z.txt)
[exception-2017-06-05T072415Z.txt](https://github.com/OpenRA/ra2/files/1051355/exception-2017-06-05T072415Z.txt)

**Comment by alexholliz** [comment]
I was able to fix that error, and another one that popped up,


```Exception of type `System.IO.FileNotFoundException`: File not found: mousepal.pal``` fixed by copying: https://github.com/Phrohdoh/oramod-ra2/blob/master/ra2/bits/mousepal.pal to ```OpenRA\mods\ra2\bits\mousepal.pal```
```Exception of type `System.IO.FileNotFoundException`: File not found: mouse.shp``` fixed by copying: https://github.com/Phrohdoh/oramod-ra2/blob/master/ra2/bits/mouse.shp to ```OpenRA\mods\ra2\bits\mouse.shp```

**Comment by alexholliz** [comment]
I am getting a new error:
[exception-2017-06-05T165516Z.txt](https://github.com/OpenRA/ra2/files/1052635/exception-2017-06-05T165516Z.txt)

This looks like an actual code error: ```Exception of type `OpenRA.YamlException`: Actor type ^amcv.colorpicker: Actors with Health need at least one HitShape trait!```

**Comment by GraionDilach** [comment]
The RA2 mod is again outdated against OpenRA bleed by a month or around.

**Comment by alexholliz** [comment]
Oh! I hadn't even considered that the mod might be out of date.

**Comment by 12sunflowers** [comment]
Same here RA2 and Dune 2 mod
https://github.com/Fincer/openra-tibsunra2/issues/9

**Comment by GraionDilach** [comment]
Pretty sure this issue won't be resolved until #386 gets merged. See m,y previous comment again.

**Comment by 12sunflowers** [comment]
so, what is solution?

**Comment by abcdefg30** [comment]
Fixed by #386 (sorry for the delay).

**Comment by hartmark** [comment]
I get this exception now on the latest code, so I guess there some more things left to get it working again.

```
System.IO.InvalidDataException occurred
  HResult=0x80131501
  Message=`VoxelSequences` is not a valid mod manifest entry.
  Source=OpenRA.Game
  StackTrace:
   at OpenRA.Manifest.LoadCustomData(ObjectCreator oc) in C:\Users\musku\Source\Repos\OpenRA\OpenRA.Game\Manifest.cs:line 153
   at OpenRA.ModData..ctor(Manifest mod, InstalledMods mods, Boolean useLoadScreen) in C:\Users\musku\Source\Repos\OpenRA\OpenRA.Game\ModData.cs:line 59
   at OpenRA.Game.InitializeMod(String mod, Arguments args) in C:\Users\musku\Source\Repos\OpenRA\OpenRA.Game\Game.cs:line 408
   at OpenRA.Game.Initialize(Arguments args) in C:\Users\musku\Source\Repos\OpenRA\OpenRA.Game\Game.cs:line 368
   at OpenRA.Program.Run(String[] args) in C:\Users\musku\Source\Repos\OpenRA\OpenRA.Game\Support\Program.cs:line 134
   at OpenRA.Program.Main(String[] args) in C:\Users\musku\Source\Repos\OpenRA\OpenRA.Game\Support\Program.cs:line 34
```

**Comment by hartmark** [comment]
@abcdefg30

**Comment by abcdefg30** [comment]
It looks like you're trying to run the mod from another OpenRA install. You should rather use `launch-game.cmd` (see https://github.com/OpenRA/ra2/wiki#installing-the-mod).

**Comment by hartmark** [comment]
Alright, I'm using the bleed branch on OpenRA and when switching to the master branch I got it working.

**Comment by hartmark** [comment]
Now I was able to startup the game and copy the ra2 assets. But after that I get this exception when trying to start the game.

OpenRA.YamlException occurred
  HResult=0x80131500
  Message=Actor type cow: Trait name AmbientSound: Required property missing: SoundFile
  Source=OpenRA.Game
  StackTrace:
   at OpenRA.ActorInfo..ctor(ObjectCreator creator, String name, MiniYaml node) in C:\Users\musku\Source\Repos\OpenRA\OpenRA.Game\GameRules\ActorInfo.cs:line 57
   at OpenRA.Ruleset.<>c__DisplayClass11_0.<LoadDefaults>b__1(MiniYamlNode k) in C:\Users\musku\Source\Repos\OpenRA\OpenRA.Game\GameRules\Ruleset.cs:line 108
   at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, String debugName, Func`2 logKey, Func`2 logValue) in C:\Users\musku\Source\Repos\OpenRA\OpenRA.Game\Exts.cs:line 376
   at OpenRA.Ruleset.MergeOrDefault[T](String name, IReadOnlyFileSystem fileSystem, IEnumerable`1 files, MiniYaml additional, IReadOnlyDictionary`2 defaults, Func`2 makeObject) in C:\Users\musku\Source\Repos\OpenRA\OpenRA.Game\GameRules\Ruleset.cs:line 93
   at OpenRA.Ruleset.<>c__DisplayClass11_0.<LoadDefaults>b__0() in C:\Users\musku\Source\Repos\OpenRA\OpenRA.Game\GameRules\Ruleset.cs:line 107
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Any ideas?

**Comment by hartmark** [comment]
Nevermind, Got it working now. I'll put a PR with a bat-file for windows hosts to fetch the OpenRA engine projects

**Comment by DanielTongAwesome** [comment]
I encounter the same issue any idea how?

**Comment by hartmark** [comment]
This was a while ago :)
The PR I was mentioning was this
https://github.com/OpenRA/ra2/pull/390

So I guess you will get it working by running the make.cmd or make.ps1
