### ISSUE TITLE
Pressing Tab after Building a Cloning Vat Crashes Game

### ISSUE THREAD

**Issue by wolfbyte** [OpenRA/ra2#526]
1. What you were doing when something broke?
  I was hitting the alt + 0 to 9 repeatedly with 5 amphibious transports selected (filled with rhino tanks). I had gotten confused as to whether it was ctrl or alt to assign the group, so I was just trying out ALT. At the time, I don't think I actually had any groups assigned. I was hitting the buttons fast, so possible race condition. 

2. What you expected to happen?
Wanted to assign a team number .
3. What actually happened?
I was dropped back to desktop. Game crashed. cmd prompt in which I had run launch-game.cmd had the following:
`
PS C:\Users\darkscrypt\ra2\ra2-master\ra2-master> .\launch-game.cmd
----------------------------------------
OpenRA has encountered a fatal error.
  * Log Files are available in Documents\OpenRA\Logs
  * FAQ is available at https://github.com/OpenRA/OpenRA/wiki/FAQ
----------------------------------------
Press any key to continue . . .

4. If it's a crash, the contents of exception.log.

OpenRA engine version release-20180923
Red Alert 2 mod version {DEV_VERSION}
on map 5dc4a06623520ebada5f73180d9273c60c96d2b1 (Official Tournament Map A by Westwood Studios).
Date: 2018-12-12 01:27:43Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at OpenRA.Mods.Common.Widgets.Logic.Ingame.CycleProductionActorsHotkeyLogic.<OnHotkeyActivated>b__1(Actor f) in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\Hotkeys\CycleProductionActorsHotkeyLogic.cs:line 43
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OpenRA.Mods.Common.Widgets.Logic.Ingame.CycleProductionActorsHotkeyLogic.OnHotkeyActivated(KeyInput e) in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\Hotkeys\CycleProductionActorsHotkeyLogic.cs:line 41
   at OpenRA.Mods.Common.Widgets.Logic.SingleHotkeyBaseLogic.<>c__DisplayClass1.<.ctor>b__0(KeyInput e) in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Mods.Common\Widgets\Logic\SingleHotkeyBaseLogic.cs:line 33
   at OpenRA.Mods.Common.Widgets.LogicKeyListenerWidget.HandleKeyPress(KeyInput e) in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Mods.Common\Widgets\LogicKeyListenerWidget.cs:line 25
   at OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e) in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Game\Widgets\Widget.cs:line 416
   at OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e) in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Game\Widgets\Widget.cs:line 412
   at OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e) in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Game\Widgets\Widget.cs:line 412
   at OpenRA.Widgets.Ui.HandleKeyPress(KeyInput e) in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Game\Widgets\Widget.cs:line 134
   at OpenRA.DefaultInputHandler.<>c__DisplayClass1.<OnKeyInput>b__0() in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Game\Input\InputHandler.cs:line 40
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn) in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Game\Sync.cs:line 183
   at OpenRA.DefaultInputHandler.OnKeyInput(KeyInput input) in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Game\Input\InputHandler.cs:line 40
   at OpenRA.Platforms.Default.Sdl2Input.PumpInput(Sdl2PlatformWindow device, IInputHandler inputHandler) in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Platforms.Default\Sdl2Input.cs:line 182
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.PumpInput(IInputHandler inputHandler) in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Platforms.Default\Sdl2PlatformWindow.cs:line 309
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler) in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Game\Renderer.cs:line 162
   at OpenRA.Game.RenderTick() in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Game\Game.cs:line 682
   at OpenRA.Game.Loop() in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Game\Game.cs:line 792
   at OpenRA.Game.Run() in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Game\Game.cs:line 810
   at OpenRA.Game.InitializeAndRun(String[] args) in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Game\Game.cs:line 256
   at OpenRA.Program.Main(String[] args) in c:\Users\darkscrypt\ra2\ra2-master\ra2-master\engine\OpenRA.Game\Support\Program.cs:line 37

`

**Comment by wolfbyte** [comment]
It happened again. This time I was trying to alt-tab out of the game, and was not trying to assign units.  I believe somehow I wasn't holding alt at the time and just hit tab and it died. 

OpenRA engine version release-20180923
Red Alert 2 mod version {DEV_VERSION}
on map d91e39777304ec497ddfd319229788c5d3d51865 (South Pacific by Westwood Studios).
Date: 2018-12-14 16:06:23Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at OpenRA.Mods.Common.Widgets.Logic.Ingame.CycleProductionActorsHotkeyLogic.<OnHotkeyActivated>b__1(Actor f) in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\Hotkeys\CycleProductionActorsHotkeyLogic.cs:line 43
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OpenRA.Mods.Common.Widgets.Logic.Ingame.CycleProductionActorsHotkeyLogic.OnHotkeyActivated(KeyInput e) in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\Hotkeys\CycleProductionActorsHotkeyLogic.cs:line 41
   at OpenRA.Mods.Common.Widgets.Logic.SingleHotkeyBaseLogic.<>c__DisplayClass1.<.ctor>b__0(KeyInput e) in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Mods.Common\Widgets\Logic\SingleHotkeyBaseLogic.cs:line 33
   at OpenRA.Mods.Common.Widgets.LogicKeyListenerWidget.HandleKeyPress(KeyInput e) in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Mods.Common\Widgets\LogicKeyListenerWidget.cs:line 25
   at OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e) in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Game\Widgets\Widget.cs:line 416
   at OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e) in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Game\Widgets\Widget.cs:line 412
   at OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e) in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Game\Widgets\Widget.cs:line 412
   at OpenRA.Widgets.Ui.HandleKeyPress(KeyInput e) in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Game\Widgets\Widget.cs:line 134
   at OpenRA.DefaultInputHandler.<>c__DisplayClass1.<OnKeyInput>b__0() in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Game\Input\InputHandler.cs:line 40
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn) in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Game\Sync.cs:line 183
   at OpenRA.DefaultInputHandler.OnKeyInput(KeyInput input) in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Game\Input\InputHandler.cs:line 40
   at OpenRA.Platforms.Default.Sdl2Input.PumpInput(Sdl2PlatformWindow device, IInputHandler inputHandler) in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Platforms.Default\Sdl2Input.cs:line 182
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.PumpInput(IInputHandler inputHandler) in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Platforms.Default\Sdl2PlatformWindow.cs:line 309
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler) in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Game\Renderer.cs:line 162
   at OpenRA.Game.RenderTick() in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Game\Game.cs:line 682
   at OpenRA.Game.Loop() in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Game\Game.cs:line 792
   at OpenRA.Game.Run() in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Game\Game.cs:line 810
   at OpenRA.Game.InitializeAndRun(String[] args) in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Game\Game.cs:line 256
   at OpenRA.Program.Main(String[] args) in c:\Users\n513336\bin\ra2-master\engine\OpenRA.Game\Support\Program.cs:line 37

**Comment by wolfbyte** [comment]
Steps to Reproduce 100% of the time
Build a cloning vat. 
Select ANY infantry unit.
Hit tab
Game Crashes. Every time. 

Long story short, this has nothing to do with team assignment.

**Comment by wolfbyte** [comment]
Even Quicker way to Reproduce
Have a Cloning Vat
Press Tab. 

Apparently it doesn't matter if you have any units selected.
