### ISSUE TITLE
RA2 Crashes on when loading mod.

### ISSUE THREAD

**Issue by FluffyFluffBall** [OpenRA/ra2#62]
This is the error is spews, and I have no idea what this means. 

Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.InvalidDataException`: Duplicate key 'ra2' in E:\OpenRA\mods\ra2\mod.yaml:13
Inner Exception of type `System.ArgumentException`: An item with the same key has already been added.
     at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OpenRA.MiniYaml.ToDictionary[TKey,TElement](Func`2 keySelector, Func`2 elementSelector)
   at OpenRA.MiniYaml.ToDictionary[TKey,TElement](Func`2 keySelector, Func`2 elementSelector)
   at OpenRA.MiniYaml.ToDictionary[TElement](Func`2 elementSelector)
   at OpenRA.MiniYaml.ToDictionary()
   at OpenRA.Manifest.YamlList(Dictionary`2 yaml, String key, Boolean parsePaths)
   at OpenRA.Manifest..ctor(String mod)
   at OpenRA.ModData..ctor(String mod, Boolean useLoadScreen)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Mods.Common.Widgets.Logic.ModBrowserLogic.<LoadMod>c__AnonStorey1.<>m__0()
   at OpenRA.Primitives.ActionQueue.PerformActions(Int32 currentTime)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by Phrohdoh** [comment]
[Line 12](https://github.com/OpenRA/ra2/blob/1a1a70cf4bfb59fb66685200683518d52fa65092/mod.yaml#L12) should probably be `ra2: .`

**Comment by FluffyFluffBall** [comment]
Changing that line did nothing, spewed out the same error.

Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.InvalidDataException`: Duplicate key 'ra2' in E:\OpenRA\mods\ra2\mod.yaml:13
Inner Exception of type `System.ArgumentException`: An item with the same key has already been added.
     at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OpenRA.MiniYaml.ToDictionary[TKey,TElement](Func`2 keySelector, Func`2 elementSelector)
   at OpenRA.MiniYaml.ToDictionary[TKey,TElement](Func`2 keySelector, Func`2 elementSelector)
   at OpenRA.MiniYaml.ToDictionary[TElement](Func`2 elementSelector)
   at OpenRA.MiniYaml.ToDictionary()
   at OpenRA.Manifest.YamlList(Dictionary`2 yaml, String key, Boolean parsePaths)
   at OpenRA.Manifest..ctor(String mod)
   at OpenRA.ModData..ctor(String mod, Boolean useLoadScreen)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Mods.Common.Widgets.Logic.ModBrowserLogic.<LoadMod>c__AnonStorey1.<>m__0()
   at OpenRA.Primitives.ActionQueue.PerformActions(Int32 currentTime)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by abcdefg30** [comment]
It seems like you're trying to run this with the latest OpenRA release, but you need to latest development version. You can find it [here](https://github.com/OpenRA/OpenRA), then just follow the guide from the [wiki](https://github.com/OpenRA/ra2/wiki#mod).

**Comment by abcdefg30** [comment]
If you have further questions, or need more assistance, feel free to join us on IRC: http://webchat.freenode.net/?channels=openra

**Comment by FluffyFluffBall** [comment]
Thank you got it to work, that helped a lot.

**Comment by foulowl** [comment]
What did you do to get this to work? I have the same issue. Latest dev version of openra.

**Comment by jtyle6** [comment]
@foulowl Make please a new one with your crash.

**Comment by Phrohdoh** [comment]
Notifications are still created for closed tickets.
This looks to me like RA2 was ran on an old version of the engine.

@abcdefg30 it would be good to document this process exactly instead of always routing to IRC.

**Comment by jtyle6** [comment]
Sorry didn't know.

**Comment by abcdefg30** [comment]
@jtyle6 no problem, you're kinda right. ;)
@foulowl could you open a new issue with the crash log attached if you still get the crash.
The problem @FluffyFluffBall was not using both the latest development version of both OpenRA and RA2.
