### ISSUE TITLE
RA2 still crashing when loading mod.

### ISSUE THREAD

**Issue by FluffyFluffBall** [OpenRA/ra2#68]
After getting past one error, I get to this error.

Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.FileNotFoundException`: Could not load file or assembly 'file:///C:\Users\Welsh\Desktop\OpenRA-bleed\mods\ra2\OpenRA.Mods.RA2.dll' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at OpenRA.ModData.<.ctor>b__0(String path) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\ModData.cs:line 48
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenRA.ObjectCreator..ctor(IEnumerable`1 sourceAssemblies) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\ObjectCreator.cs:line 29
   at OpenRA.ModData..ctor(String mod, Boolean useLoadScreen) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\ModData.cs:line 49
   at OpenRA.Game.InitializeMod(String mod, Arguments args) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 342
   at OpenRA.Mods.Common.Widgets.Logic.ModBrowserLogic.<>c__DisplayClass28.<LoadMod>b__26()
   at OpenRA.Primitives.ActionQueue.PerformActions(Int32 currentTime) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Primitives\ActionQueue.cs:line 52
   at OpenRA.Game.LogicTick() in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 574
   at OpenRA.Game.Loop() in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 709
   at OpenRA.Game.Run() in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 749
   at OpenRA.Program.Run(String[] args) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 117
   at OpenRA.Program.Main(String[] args) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 39

**Comment by penev92** [comment]
I'm almost certain that this is now listed in the README after there were 5 such reports over the last 2 weeks.

**Comment by FluffyFluffBall** [comment]
I can't find anything relating to this, I may just be blind.

**Comment by penev92** [comment]
See https://github.com/OpenRA/ra2/issues/31

**Comment by abcdefg30** [comment]
You need to compile the `ra2.dll`.

**Comment by FluffyFluffBall** [comment]
Okay, now I have this issue after my attempt at compiling. 

Mod Chooser Mod at Version {DEV_VERSION}
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenRA.Game.IsModInstalled(String modId) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 296
   at OpenRA.Exts.GetOrAdd[K,V](Dictionary`2 d, K k, Func`2 createFn) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Exts.cs:line 130
   at OpenRA.Primitives.Cache`2.get_Item(T key) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Primitives\Cache.cs:line 35
   at OpenRA.Mods.Common.Widgets.Logic.ModBrowserLogic.SelectMod(ModMetadata mod)
   at OpenRA.Mods.Common.Widgets.Logic.ModBrowserLogic.<>c__DisplayClass20.<RebuildModList>b__1b()
   at OpenRA.Mods.Common.Widgets.ButtonWidget.<.ctor>b__29(MouseInput mi)
   at OpenRA.Mods.Common.Widgets.ButtonWidget.HandleMouseInput(MouseInput mi)
   at OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:line 369
   at OpenRA.Widgets.Ui.HandleInput(MouseInput mi) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:line 87
   at OpenRA.DefaultInputHandler.<>c__DisplayClass7.<OnMouseInput>b__6() in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Input\InputHandler.cs:line 49
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Sync.cs:line 178
   at OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Input\InputHandler.cs:line 49
   at OpenRA.Platforms.Default.Sdl2Input.PumpInput(IInputHandler inputHandler) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Platforms.Default\Sdl2Input.cs:line 106
   at OpenRA.Platforms.Default.Sdl2GraphicsDevice.PumpInput(IInputHandler inputHandler) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Platforms.Default\Sdl2GraphicsDevice.cs:line 353
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Renderer.cs:line 156
   at OpenRA.Game.RenderTick() in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 621
   at OpenRA.Game.Loop() in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 731
   at OpenRA.Game.Run() in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Game.cs:line 749
   at OpenRA.Program.Run(String[] args) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 117
   at OpenRA.Program.Main(String[] args) in c:\Users\Welsh\Desktop\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 39

**Comment by Mailaender** [comment]
You are probably not on the latest revision of https://github.com/OpenRA/OpenRA/tree/bleed

**Comment by FluffyFluffBall** [comment]
I'm currently running the latest and it still happens.

**Comment by Mailaender** [comment]
Can't reproduce. Stick to https://github.com/OpenRA/ra2/wiki#installation
